### PR TITLE
startify fix

### PR DESCRIPTION
**Pull request by ChrisTsou**
This fixes startify opening when you close a buffer but there still is a buffer remaining. from [here](https://github.com/mhinz/vim-startify/issues/424)

### CODE REVIEW

**Comment by ChrisTsou** [comment]
ok there is a problem with this... if you open an empty file it opens startify...

**Comment by Blacksuan19** [comment]
startify doesn't start when a buffer is closed and there is another left for me

**Comment by ChrisTsou** [comment]
yeah i was a bit off.  it happens when you open a split from fzf. open a file -> leader f -> open file with C-v -> close new window with leader q -> startify appears even though the first window is there.

**Comment by Blacksuan19** [comment]
yeah it happens when a split is opened from fzf, will take a deeper look into it later on

**Pull request closed without merging**
